name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      - name: Install Poetry dependencies
        run: |
          poetry install --no-root

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      - name: Install Poetry dependencies
        run: |
          poetry install --no-root
      - name: Run lint
        run: |
          poetry run task lint
      - name: Run formatter
        run: |
          poetry run task formatter
      - name: Run security tests
        run: |
          poetry run task security

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3
      - name: Install Poetry dependencies
        run: |
          poetry install --no-root
      - name: Run unit tests
        run: |
          poetry run task test
